variables:
  MIRROR_REPO: git@github.com:thm-projects/arsnova-mobile.git
  WAR_FILE: target/arsnova-mobile.war

stages:
  - analysis
  - build
  - deploy
  - synchronization

cache:
  paths:
    - node_modules/

sync_mirror:
  stage: synchronization
  when: always
  tags:
    - git
  allow_failure: true
  script:
    - git clone --bare "$CI_REPOSITORY_URL" mirror.git
    - mkdir ~/.ssh && echo "$GITHUB_HOST_KEY" > ~/.ssh/known_hosts
    - eval $(ssh-agent -s) && ssh-add <(echo "$GITHUB_DEPLOY_KEY")
    - cd mirror.git
    - git update-ref -d refs/tags/production
    - git update-ref -d refs/tags/staging
    - git push --mirror "$MIRROR_REPO"

jshint:
  stage: analysis
  tags:
    - nodejs
  script:
    - npm install -g grunt-cli
    - npm install
    - grunt jshint

jscs:
  stage: analysis
  tags:
    - nodejs
  script:
    - npm install -g grunt-cli
    - npm install
    - grunt jscs

sonar:
  stage: analysis
  only:
    - master
  tags:
    - maven
  allow_failure: true
  script:
    - mvn sonar:sonar

package:
  stage: build
  tags:
    - nodejs
    - sencha
  artifacts:
    paths:
      - $WAR_FILE
  script:
    - npm install -g grunt-cli
    - npm install
    - grunt package

tomcat_production:
  stage: deploy
  only:
    - production
  script:
    - curl --fail --upload-file "$WAR_FILE" "https://$PROD_TOMCAT_USER:$PROD_TOMCAT_PASSWORD@$PROD_TOMCAT_HOST/manager/text/deploy?path=%2Fmobile&update=true"

tomcat_development:
  stage: deploy
  only:
    - staging
  script:
    - curl --fail --upload-file "$WAR_FILE" "https://$DEV_TOMCAT_USER:$DEV_TOMCAT_PASSWORD@$DEV_TOMCAT_HOST/manager/text/deploy?path=%2Fmobile&update=true"
